version: '3.0'
services:
  app:
    build: .
    container_name: challenge
    command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/home/challenge/app
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_DB: "challenge"
